name: Problem Matchers
on:
  push:
    paths:
      - 'scripts/generate-actionlint-matcher/*.js'
      - 'testdata/examples/*.out'
      - 'testdata/err/*.out'
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  matcher-test:
    name: Test generate-actionlint-matcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout@v5
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # actions/setup-go@v6
        with:
          go-version: '1.25'
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: npm
          cache-dependency-path: ./playground/package-lock.json
      - name: Update test data
        run: make ./scripts/generate-actionlint-matcher/test/* SKIP_GO_GENERATE=true
      - name: Test actionlint-matcher.json
        run: node ./scripts/generate-actionlint-matcher/test.mjs
      - name: Ensure .github/actionlint-matcher.json is up-to-date
        run: |
          make .github/actionlint-matcher.json
          if git diff --quiet; then
            echo 'OK'
          else
            echo 'ERROR! .github/actionlint-matcher.json is outdated. Update it by "make .github/actionlint-matcher.json"' >&2
            set -x
            git diff
            exit 1
          fi
