name: Release to dbt/ghcr
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  binaries:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: gem install ronn
      - run: ronn ./man/actionlint.1.ronn
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get tag name
        id: tag
        run: |
          echo "name=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FA_ASSISTANT_CI_WORKFLOW_PAT_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            GOLANG_VER=1.25
            ACTIONLINT_VER=${{ steps.tag.outputs.name }}
          push: true
          tags: |
            ghcr.io/dbt-labs/actionlint:${{ steps.tag.outputs.name }}
